spring:
  datasource:
    url: jdbc:postgresql://192.168.178.26:5432/vehicle
    username: vc
    password: secret
    tomcat:
      max-active: 5000

server:
  tomcat:
    threads:
      max: 100

webservice:
  url: 192.168.178.26:8090