micronaut:
  application:
    name: micronautReactive
#  http:
#    client:
#      num-of-threads: 50
#  netty:
#    event-loops:
#      num-threads: 200

webservice:
  url: http://localhost:8090

r2dbc:
  datasources:
    default:
      dialect: POSTGRES
      url: r2dbc:postgresql://192.168.178.26:5432/vehicle
      username: vc
      password: secret